$JOBS
WKSTN00001#JB00001
 SCRIPTNAME "/home/tutor/script.sh parameter_01"
 STREAMLOGON sysacctbj01
 DESCRIPTION "THIS IS JOB DEFINITION"
 TASKTYPE UNIX
 RECOVERY STOP

WKSTN00002#JB00002
 SCRIPTNAME "/home/tutor/script.sh parameter_01"
 STREAMLOGON sysacctbj01
 DESCRIPTION "THIS IS JOB DEFINITION"
 TASKTYPE UNIX
 RECOVERY STOP